web_store/store/urls.py
from django.urls import path
from . import views

app_name = 'store'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('stock_page/<int:storeItem_id>', views.stock_page, name='stock_page'),
    path('confirmation_page/<int:stockItem_id>', views.confirmation_page, name='confirmation_page'),
    path('successful_reg_page/', views.successful_reg_page, name='successful_reg_page'),
    path('successful_order/', views.successful_order, name='successful_order'),
]

web_store/user_authorisation/urls.py
from django.urls import path, include
from . import views

app_name = 'user_auth'
urlpatterns = [
    #path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('create_user/', views.create_user, name='create_user'),
    path('store_login/', views.store_login, name='store_login'),
]

web_store/web_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user_authorisation import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('user_auth/', include("django.contrib.auth.urls")),
    path('user_auth/', include("user_authorisation.urls")),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_store/store/models.py
from django.db import models

# Logos Class
class storeItem(models.Model):
    """This is a class that store info about the 
    shoes in the database

    :param image: Shoe image
    :param info: Shoe info
    :param brand: Shoe brand

    """

    image = models.ImageField(upload_to='images/')
    info = models.CharField(max_length=200)
    brand = models.CharField(max_length=200, default='brand')

    def __str__(self):
        """Return a str version of an object
        """
        return self.info
    
# Stock Class
class stockItem(models.Model):
    """This is a class that stores info about the 
    stock in the database

    :param image: Shoe image
    :param info: Shoe info
    :param brand: Shoe brand
    """
    image = models.ImageField(upload_to='images/')
    info = models.CharField(max_length=200)
    brand = models.CharField(max_length=200, default='brand')
    price = models.CharField(max_length=200, default='price')

    def __str__(self):
        """Return a str version of an object
        """
        return self.info
    

web_store/user_authorisation/models.py
from django import forms

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=130)
    password = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=20)

web_store/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import storeItem, stockItem

# Create your views here.
def home_page(request):
    """This function takes user to homepage 

    :param request: Client request
    :return: rendered html
    """
    items = storeItem.objects
    return render(request, 'store_templates/home_page.html', {'items': items})

def stock_page(request, storeItem_id):
    """This function takes user to the stock page

    :param request: Client request
    :param storeItem_id: store item id
    :return: rendered html
    """
    brand = get_object_or_404(storeItem, pk=storeItem_id)
    items = stockItem.objects.all()
    return render(request, 'store_templates/stock_page.html', {'brand': brand, 'items': items})

def confirmation_page(request, stockItem_id):
    """This function takes user to the order confirmation page

    :param request: Client request
    :param storeItem_id: stock id
    :return: rendered html
    """
    item = get_object_or_404(stockItem, pk=stockItem_id)
    return render(request, 'store_templates/confirmation_page.html', {'item': item})


def successful_reg_page(request):
    """This function takes user to successful registration page 

    :param request: Client request
    :return: rendered html
    """
    return render(request, 'store_templates/successful_reg.html', {})


def successful_order(request):
    """This function takes user to successful order page 

    :param request: Client request
    :return: rendered html
    """
    return render(request, 'store_templates/successful_order.html', {})

web_store/user_authorisation/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from . import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your views here.
def authenticate_user(request):
    username = request.POST.get('username','')
    password = request.POST.get('password','')
    user = authenticate(username=username, password=password)
    if user is None:
        return HttpResponseRedirect(
            reverse('user_auth:store_login')
        )
    else:
        login(request, user)
        return HttpResponseRedirect(
            reverse('store:home_page')
    )

def create_user(request):
    if request.method == 'POST':
        form = models.RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']     
            password = form.cleaned_data['password']
            first_name = form.cleaned_data['first_name']
            User.objects.create_user(username=username, password=password, first_name=first_name)
            return render(request, 'store_templates/successful_reg.html', {})  
    else:
        form = models.RegistrationForm()
    return render(request, 'user_templates/create_user.html', {'form': form})

def store_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('store:successful_order')
        
        else:
            return redirect('user_auth:store_login') 

    return render(request, 'user_templates/store_login.html', {})

web_store/store/templates/store_templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>KICKS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Cards Style -->
    <div class="container">
        <style>
          .right-item {
              float: right;
          }
        
    /* Styling for the navigation bar */
          .navbar {
            background-color: #f1f1f1; 
            padding: 8px; 
            display: flex; 
            align-items: center; 
          }
        
          .navbar-brand {
            font-size: 60px; 
            margin-right: auto; 
            text-decoration: none; 
            color: #333;
          }

          .nav-link {
            text-decoration: none; 
            color: #333; 
            margin-left: 15px; 
          }

    /* Styling for the footer */
          footer {
            margin-top: 10px; 
            text-align: center; 
          }
        
    /* Styling for the line before the footer */
          .footer-line {
            border-top: 1px solid #a7a6a6;
            margin: 40px auto; 
            width: 60%; 
          }       
        </style>
    </div>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar">
      <a class="navbar-brand" href="/">KICKS</a>
      <a class="nav-link" href="#">About</a>
      <a class="nav-link" href="#">Contact</a>
      <a class="nav-link" href="#">Careers</a>
    </nav>

    {% block content %}{% endblock content %}

    <div class="footer-line"></div>

    <footer class="text-muted" style="text-align: center;">
      <div class="container">
        <p class="float-right" style="font-size: 15px;">
          <a href="#">Back to top</a>
        </p>
        <p style="font-size: 12px;">KICKS is a proudly SA brand, with 80% of our material sourced locally</p>
        <p style="font-size: 12px;">
          Give us a shout <a href="mailto:john@gmail.com">mail</a>.</p>
        </p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>

</body>
</html>

web_store/store/templates/store_templates/confirmation_page.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<!-- Confirmation Content -->
<main role="main" style="margin-top: 50px;">
    <section class="jumbotron text-center">

      <div class="container">
        <img src="{% static 'logo.jpg' %}" height=150></img>
        <h1 class="jumbotron-heading">Comfirm Order</h1>
        <p class="lead text-muted" style="margin-bottom: 40px;">Please confirm order!</p>
        <img src="{{ item.image.url }}" height=300></img>
        <p style="margin-top: 20px;"> 
          <a href="{% url 'user_auth:store_login' %}" class="btn btn-dark my-2">Confirm</a> 
          <a href="{% url 'store:home_page' %}" class="btn btn-dark my-2">Cancel</a>
        </p>
      </div>

    </section>
    </main>
{% endblock content%}





 

web_store/store/templates/store_templates/form_fail.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<main role="main">
    <section class="jumbotron text-center">
      <div class="container">
        <img src="{% static 'logo.jpg' %}" height=150></img>
        <h1 class="jumbotron-heading">Comfirm Order</h1>
        <p class="lead text-muted">{% message %}!</p>
        <img src="{{ item.image.url }}" height=300></img>
        <p>
          <a href="#" class="btn btn-primary my-2">Confirm</a>
          <a href="{% url 'home_page' %}" class="btn btn-primary my-2">Cancel</a>
        </p>

      </div>
    </section>
    </main>
{% endblock content%}



 

web_store/store/templates/store_templates/home_page.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<!-- Logo and information and instructions -->
<main role="main" style="margin-top: 50px;">
    <section class="jumbotron text-center">
      <div class="container">
        <img src="{% static 'logo.jpg' %}" height=150></img>
        <h1 class="jumbotron-heading">Brands</h1>
        <p class="lead text-muted">select from some of the world's best shoe brands</p>
        <p>
          <a href="mailto:john@gmail.com" class="btn btn-dark my-2">Help</a>
        </p>

      </div>
    </section>

    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row">
          <!-- Loop through brands -->
          {% for item in items.all %}
          <div class="col-md-4"> 
            <a href="{% url 'store:stock_page' item.id %}">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ item.image.url }}" alt="shoe brand">
                <div class="card-body">
                  <p class="btn btn-secondary my-2">{{ item.info }}</p>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
    
    </main>
{% endblock content%}



 

web_store/store/templates/store_templates/stock_page.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<!-- Logo and information and instructions -->
<main role="main" style="margin-top: 50px;">
    <section class="jumbotron text-center">
      <div class="container">
        <img src="{% static 'logo.jpg' %}" height=150></img>
        <h1 class="jumbotron-heading">{{brand.brand}}</h1>
        <p class="lead text-muted">select from some of the world's best shoe brands</p>
        <p>
          <a href="{% url 'store:home_page' %}" class="btn btn-dark my-2">Home</a>
        </p>
      </div>
    </section>

      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            <!-- Loop through stock or shoes -->
            {% for item in items.all %}
              {% if brand.brand|lower == item.brand|lower %}
                <div class="col-md-4">
                  <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="{{ item.image.url }}" alt="shoe brand">
                    <div class="card-body">
                      <p class="card-text">{{ item.info }}</p>
                          <a href="{% url 'store:confirmation_page' item.id%}" class="btn btn-secondary my-2">Buy now</a>                          
                          <div class="right-item">
                            <p class="card-text">{{ item.price }}</p>
                          </div>          
                    </div>
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </main>
{% endblock content%}



 

web_store/store/templates/store_templates/successful_order.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<!-- Logo and information and instructions -->
<main role="main" style="margin-top: 50px;">
    <section class="jumbotron text-center">
      <div class="container">
        <img src="{% static 'logo.jpg' %}" height=150></img>
        <h1 class="jumbotron-heading">Order Captured</h1>
        <p class="lead text-muted">Thank you for shopping with KICKS!</p>
        <img src="{{ item.image.url }}" height=300></img>
          <p>
            <a href="{% url 'store:home_page' %}" class="btn btn-dark my-2">Home</a>
          </p>
      </div>
    </section>
    </main>
{% endblock content%}




 

web_store/store/templates/store_templates/successful_reg.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<!-- Logo and information and instructions -->
<main role="main" style="margin-top: 50px;">
    <section class="jumbotron text-center">
      <div class="container">
        <img src="{% static 'logo.jpg' %}" height=150></img>
        <h1 class="jumbotron-heading" style="margin-bottom: 40px;">Registration Successful!</h1>
        <p>
          <a href="{% url 'store:home_page' %}" class="btn btn-dark my-2">Home</a>
          <a href="{% url 'store:successful_order' %}" class="btn btn-dark my-2">Confirm Order</a>
       </p>
      </div>
    </section>
    </main>
{% endblock content%} 




 

web_store/user_authorisation/templates/user_templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>KICKS</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Cards Style -->
    <div class="container">
        <style>
          .right-item {
              float: right;

          }
          
    /* Styling for the navigation bar */
          .navbar {
            
            background-color: #f1f1f1; 
            padding: 8px; 
            display: flex; 
            align-items: center; 
          }
        
          .navbar-brand {
            font-size: 60px; 
            margin-right: auto; 
            text-decoration: none; 
            color: #333;
          }

          .nav-link {
            text-decoration: none; 
            color: #333; 
            margin-left: 15px; 
          }

    /* Styling for the footer */
          footer {
            margin-top: 10px; 
            text-align: center; 
          }
        
    /* Styling for the line before the footer */
          .footer-line {
            border-top: 1px solid #a7a6a6;
            margin: 40px auto; 
            width: 60%; 
          }
      
        
        </style>
    </div>

  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar">
      <a class="navbar-brand" href="/">KICKS</a>
      <a class="nav-link" href="#">About</a>
      <a class="nav-link" href="#">Contact</a>
      <a class="nav-link" href="#">Careers</a>
    </nav>

    {% block content %}{% endblock content %}

    <div class="footer-line"></div>

    <footer class="text-muted" style="text-align: center;">
      <div class="container">
        <p class="float-right" style="font-size: 15px;">
          <a href="#">Back to top</a>
        </p>
        <p style="font-size: 12px;">KICKS is a proudly SA brand, with 80% of our material sourced locally</p>
        <p style="font-size: 12px;">
          Give us a shout <a href="mailto:john@gmail.com">mail</a>.</p>
        </p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>

</body>
</html>

web_store/user_authorisation/templates/user_templates/create_user.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<style>
    /* Center the container */
    .center-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 80vh; /* Set the container's height to 100% of the viewport height */
    }
  
    /* Style the heading */
    h1 {
      font-size: 60px;
      font-weight: bold;
      margin-bottom: 20px;
    }
  
    /* Style the form */
    form {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
    }
  
    /* Style the labels and inputs */
    label {
      font-weight: bold;
      margin-bottom: 10px; /* Set the margin between labels */
    }
  
    input {
      padding: 5px;
      margin: 5px;
    }
  
    /* Style the small text below the form */
    small {
      margin-top: 10px;
    }
  </style>
  
<!-- Form container -->
<div class="center-container">
    <h1>User Registration</h1>

    <!--reg Form-->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
</div>

{% endblock content%}

web_store/user_authorisation/templates/user_templates/register.html
{% extends "user_templates/base.html" %}  
{% block content %}

<main role="main">
    <section class="jumbotron">
        <div class="container">
            <h1 class="jumbotron-heading">{{ brand.brand }}</h1>
                <div class="content-section">

                    <!-- reg Form -->
                    <form method="POST">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ form.as_p }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Sign Up</button>
                        </div>
                    </form>

                    <div class="border-top pt-3">
                        <small class="text-muted">
                            Already Have an Account? <a class="ml-2" href="{% url 'register/store_login' %}">Sign in</a>  
                        </small>
                    </div>
                </div>
            </div> 
        </section>  
    </main>         
{% endblock content %}

web_store/user_authorisation/templates/user_templates/store_login.html
{% extends "store_templates/base.html" %}
{% load static %}
{% block content %}

<style>
  /* Center the container */
  .center-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 80vh; /* Set the container's height to 100% of the viewport height */
  }

  /* Style the heading */
  h1 {
    font-size: 60px;
    font-weight: bold;
    margin-bottom: 20px;
  }

  /* Style the form */
  form {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  /* Style the labels and inputs */
  label {
    font-weight: bold;
    margin-bottom: 10px; /* Set the margin between labels */
  }

  input {
    padding: 5px;
    margin: 5px;
  }

  /* Style the small text below the form */
  small {
    margin-top: 10px;
  }
</style>

<!-- Form container -->
<div class="center-container">
  <h1>Store Login</h1>

    <form action="{% url 'user_auth:store_login' %}" method="post">
      {% csrf_token %}
    
      <label>Username</label>
      <input type="text" name="username" placeholder="User" required>
    
      <label>Password</label>
      <input type="password" name="password" required>
    
      <input type="submit" value="Login" />
      <small>Don't have an account? <a href="{% url 'user_auth:create_user' %}">Create Account</a></small>
    </form>
</div>

{% endblock content%}